### ISSUE TITLE
Geo-location and reputation data types 

### ISSUE THREAD

**Issue by arcbtc** [fiatjaf/nostr#19]
Can we have geo-location and reputation data types?  
That way we can make a nostr-Uber. It would also be useful for nostr-prostitutes.

In fact reputation is an important one as we can use it for market stuff like Diagon Alley.

Just time-stamping the concepts, and looking forward to helping build them at the hackathon.

**Comment by fiatjaf** [comment]
Covered by https://github.com/fiatjaf/nostr/issues/20

**Comment by arcbtc** [comment]
I dont see where this is covered?
