### ISSUE TITLE
comparison to iris.to

### ISSUE THREAD

**Issue by VzxPLnHqr** [fiatjaf/nostr#23]
I do not yet have a telegram account, otherwise I would post this in there. Have you seen https://iris.to ? (seems to also be created by bitcoiners). I would like to know your thoughts as to why nostr is or will be better. Or perhaps they are quite similar in underlying design?

P.S. How close is nostr to being usable for bootstrapping itself? In other words, when will the primary support / dev channel for nostr being administered on nostr itself rather than Telegram?

**Comment by fiatjaf** [comment]
Hey @VzxPLnHqr, come chat on https://t.me/nostr_protocol about these topics.
