### ISSUE TITLE
[NIP-01] The `event.id` field acts more like a checksum than a UID

### ISSUE THREAD

**Issue by lenormf** [fiatjaf/nostr#24]
Why are event `id` fields so hard to compute? Are there real chances of collisions when generating a UID with sha256 over random data? It seems redundant with the `sig` field.

**Comment by fiatjaf** [comment]
Because the idea is that it is a checksum, the same event always has the same id everywhere, guaranteed. Isn't that a nice property?

**Comment by lenormf** [comment]
Why not make the client use less expensive computation to generate `id` (most high level languages have that in their standard library nowadays)? The same event that has to be propagated to various targets will be copied as-is, so it shouldn’t matter that the current way of generating a UID acts as a checksum.

And since the whole thing is signed, then the integrity feature that we would get from a checksum is de facto already there, from what I understand.

So why go for the complex UID generation algorithm, if not to prevent that there are no collisions (and assuming I didn’t miss anything above)?

**Comment by fiatjaf** [comment]
Why do you hate hashes? SHA256 is not complex and it's not expensive, and it's built-in in all languages' standard libraries.

To me having a deterministic ID to each event is a good thing, for example, in which it prevents unintended duplicates, it prevents confusion between users and clients when referring to events, besides being cool and simple. It's actually _easier_ for implementors to implement a sha256-based ID than to make them think about how to properly generate a random id and all the mental confusion that question might generate.

Last thing: the signature algorithm actually signs a 32-byte hash, not the full event -- coincidentally (or not) the hash that it signs is the sha256 that constitutes the event id. So everybody would have to be aware of and compute this hash anyway to verify the signature. It's better to just make it be _the id_ already.
