### ISSUE TITLE
[NIP-01] Only events are required to be signed, not `REQ`s or `CLOSE`s

### ISSUE THREAD

**Issue by lenormf** [fiatjaf/nostr#25]
Messages that have critical side effects should probably be signed, for security reasons.

**Comment by fiatjaf** [comment]
These things don't have critical side effects, they're just asking for data. If they were signed that would mean absolutely nothing as anyone could sign them. Clients would probably use random keys to sign them, making these signatures completely useless..

**Comment by lenormf** [comment]
How could anyone sign an arbitrary client’s request to close their own connections?

I’m thinking of cases where clients accidentally allow users to inject events into the websocket traffic to the relay (XSS and other injections).

**Comment by fiatjaf** [comment]
I don't understand how that could be possible. And if it is, how signing would help. We must keep in mind that websocket connections are established over TLS with wss:// (although Nostr doesn't mandate it, you could do it over ws:// too, but that is a user choice).
