### ISSUE TITLE
[NIP-01] `REQ` might be a misnommer

### ISSUE THREAD

**Issue by lenormf** [fiatjaf/nostr#27]
Relays must remember `REQ`s and return events that matches the given filter after the request has been processed.

Maybe `REQ`s should have the relay return a set of specific events one time (e.g. to fetch old events that the client remembers the `id` of, but hasn’t kept in memory/cache entirely).

Maybe “subscribing” to future messages that match the filter should be trigger via a field in `REQ`, or a new type of message entirely (`SUB`?).

There should probably also be a way to “unsubscribe”, to prevent relays from sending information that isn’t needed any more.

**Comment by fiatjaf** [comment]
I agree it can be a misnomer, but I don't think changing it now is worth the hassle.

The way to unsubscribe is the `CLOSE` message.

Relays are free to not actually subscribe anyone, and just return some events then nothing else. It's impossible to enforce that anyway.

My rationale is the following: if we had two kinds of messages, "req" and "sub", for example, then we could have relays that would implement one but not the other and that would be ok. So for now let's just keep both alternatives in the same request and expect relays to do it in the prescribed way, but not rely on it.

If clients just want a set of events and not a subscription they can just send a `CLOSE` after some seconds or something like that.

**Comment by lenormf** [comment]
Clients have to keep a connection permanently open to a relay to see events produced by other users they subscribed to? I thought the connection could be closed at will, and the relay would keep in memory the list of filters requested.

**Comment by fiatjaf** [comment]
Yes, they have to keep the connection open. I'm not sure this is wasteful or not. In the initial draft we had a simple HTTP request to fetch stuff, but then it became very clear that for a good experience most apps need real-time events pushed into the user screen somehow. So instead of making an extra "subscription" protocol along with a default "fetch" protocol I just removed the "fetch" and kept only the "subscription".
