### ISSUE TITLE
[NIP-01] Data retention of relays

### ISSUE THREAD

**Issue by lenormf** [fiatjaf/nostr#28]
How long should relays be required to store events? Or are all expected to be available at any point in the future?

**Comment by fiatjaf** [comment]
Relays are not expected to store events, this is a policy decision by each relay.

One relay might want to only relay stuff from selected members and store everything, or filter by topic etc. Other relays may charge a fee to store things, others may want to be just fast, temporary stores.

**Comment by lenormf** [comment]
[I misunderstood how relays handle connections](https://github.com/fiatjaf/nostr/issues/27#issuecomment-977952690), I suppose this is not relevant!
