### ISSUE TITLE
[NIP-01] A `resource` event kind to allow uploading blobs to a relay

### ISSUE THREAD

**Issue by lenormf** [fiatjaf/nostr#31]
If uploading files directly to a regular relay is not desirable, maybe a separate “file server” relay could be setup that accepts only a `resource` event type. The `content` field would be a blob.

Files uploaded to this relay could later be referenced in regular events, via a URL in the message’s body.

The difference with uploading the file to e.g. an HTTP file server is that the files would be kept “in closer proximity” with the events or user metadata (`picture`).

**Comment by fiatjaf** [comment]
I think the "closer proximity" is not sufficient to introduce this. For now I don't see the reason why the relay should be hosting files if that's an entirely separate feature that can be provided by other services out there.

A more compelling argument in my mind would be to reuse the Nostr infrastructure have a unified API for hosting files -- in form of events. But I don't think this is a good argument either.
