### ISSUE TITLE
[NIP-01] Add `pubkey` to the `set_metadata` event type

### ISSUE THREAD

**Issue by lenormf** [fiatjaf/nostr#32]
A public key is as part of a user’s local identity as their name or picture. Clients could also use this information to validate past events with a user’s previous or current identity.

**Comment by fiatjaf** [comment]
Each event already has a pubkey and are signed with it. `set_metadata` only specifies the `content` of an event, all the rest is the same.

**Comment by lenormf** [comment]
Yes, I guess I meant that from reading the example event in NIP-01, it looks like the only metadata users are expected to have (which could be exposed by the relay somehow) do not include the public key.

Maybe the expected format for user metadata (if only to help relay implementations know exactly what to store/expect) could be documented in a separate subsection?

**Comment by fiatjaf** [comment]
You mean this?

![2021-11-24-225506_687x467_scrot](https://user-images.githubusercontent.com/1653275/143362742-4b1951f6-e985-4da0-bebb-be8793af00fc.png)

All events have pubkey and signature already, including the `set_metadata` event.

I agree the NIP text could be improved, though.

**Comment by lenormf** [comment]
I meant this line:

https://github.com/fiatjaf/nostr/blob/97786e31423b45239306323a9a297188d20dbf21/nips/01.md?plain=1#L93-L93

`pubkey` is not part of the object passed via `content`.

**Comment by fiatjaf** [comment]
It's not, because that would be redundant and weird, since the actual event is something like 

```
{
  id: <32-bytes sha256 of the the serialized event data>
  pubkey: <32-bytes hex-encoded public key of the event creator>,
  created_at: <unix timestamp in seconds>,
  kind: <integer>,
  tags: []
  content: "{name: <string>, about: <string>, picture: <url, string>}",
  sig: <64-bytes signature of the sha256 hash of the serialized event data, which is the same as the "id" field>,
}
```

**Comment by lenormf** [comment]
It looks like there’s still confusion around what I’m asking, so I’ll reiterate.

It looks like relays are aware of certain metadata that are associated with users. We can tell because the fields that can be updated are [documented in NIP-01](https://github.com/fiatjaf/nostr/blob/97786e31423b45239306323a9a297188d20dbf21/nips/01.md?plain=1#L93-L93).

Users know about other users because relays return these metadata. They should be documented in their own subsection of NIP-01 for clarity’s sake. Relays should also return a `pubkey` as part of the metadata for a given user, because that information is as much part of the identity of the user as `name` or `picture`.

The fact that an event also has a `pubkey` field is not important, because the metadata can contain a different `pubkey` than the one used to sign the event. Even if it couldn’t, it’s part of the *technical* part of the protocol, not the user-facing one.

**Comment by fiatjaf** [comment]
No, relays don't return "metadata", they only return events. Relays don't have to know what is metadata and what isn't. 
 Relays can be completely blind with regards to what is in the event contents if they want. The only requirement for relays is that they return _full events_ to clients, including pubkeys, id, signatures etc.

It's the job of the _clients_ to associate pubkeys from the "technical part" with the metadata from the "user-facing part".

The basic assumption of Nostr is that each user has a keypair and signs all events they publish with that keypair. Therefore, if any user publishes a `set_metadata` event, that _necessarily_ means that the given metadata has to be associated with their pubkey and not with someone else's pubkey.
