### ISSUE TITLE
[NIP-01] Add `until` to subscriptions

### ISSUE THREAD

**Issue by scsibug** [fiatjaf/nostr#39]
Allow subscriptions to define time ranges to retrieve events will allow paging-like behavior for clients.

This would be done with the addition of an `until` field to request filters. `until` should match all events up to but not including the specified timestamp (exclusive range).

**Comment by scsibug** [comment]
I've implemented as described above in my rust relay (https://git.sr.ht/~gheartsfield/nostr-rs-relay/commit/100f890284bfbcfa9551f5faf2c7bd904381e9cd), in case anyone wants to test this out, it is currently running here: wss://nostr-pub.wellorder.net

**Comment by fiatjaf** [comment]
Added it to Relayer here: https://github.com/fiatjaf/relayer/commit/b4f94b8fdd0452d943be21f6b6978fc76b14999a
