### ISSUE TITLE
Feature Req: Fediverse bridge

### ISSUE THREAD

**Issue by FruityWelsh** [fiatjaf/nostr#47]
It would be cool for fediverse users/groups to be able to followed on nostr and vice versa, allowing for the two systems to exist together as needed (for example peertube instances or users that prefer the Mastadon model).

Understandably, this maybe early for this project's development cycle, but I figure I would at least through it on the backlog.

**Comment by fiatjaf** [comment]
It's been on my backlog for a while :P

**Comment by fiatjaf** [comment]
Closed because this repo is not a place for requests of this kind.

**Comment by FruityWelsh** [comment]
> Closed because this repo is not a place for requests of this kind.

Where would be a better place to track this kind of request?

**Comment by snarfed** [comment]
This now exists! https://mostr.pub/
