### ISSUE TITLE
Feature Req: Relay identification command

### ISSUE THREAD

**Issue by scsibug** [fiatjaf/nostr#50]
Floating an idea for a new optional command (to be codified in a NIP soon).  Clients should be able to request relay info, using a command like ["RELAY_INFO"].  The relays could then respond with something like:

```
["SERVER_INFO",
  {
    "name": "Nostr Dev Discussions",
    "admin_pubkey": "48f475e1acc18ba4...",
    "admin_email": "support@nostr.example.com",
    "supported_nips": ["NIP-01", "NIP-02", "NIP-09"...],
    "software": "nostr-rs-relay",
    "version": "0.3.0",
    "public_write": true
  }
]
```

**Comment by scsibug** [comment]
Eventually a protocol version could be included as well, but since everything is still draft, that may be premature for now.

**Comment by melvincarvalho** [comment]
Love this idea.  If the relay is similar to a nostr user, it can also send messages, which is pretty cool

Slight nit, perhaps just `email` and `pubkey` instead of the admin_ prefix as that's implied, or the role could be a field if its ever needed

**Comment by fiatjaf** [comment]
I think this should be an HTTP endpoint instead, as it will very likely be called manually and websockets are kind of hassle.

Nostr uses websockets as its core communication method because it's intended to have real-time push updates of events to clients -- and not using websocket would mean people would be polling, and polling is awful in all aspects. But for this I think it would be a single call for the life of the client -- or manual calls from implementors, so HTTP is best.

**Comment by melvincarvalho** [comment]
@fiatjaf I largely agree.  It's also great that nostr messages are to a degree transport agnostic, that's a good sign.  Also good to use the right protocol for the right job

Just wondering for what about those (like me) that have https hosting [branle](https://github.com/fiatjaf/branle) and wss hosting a [relay](https://github.com/fiatjaf/relayer/tree/master/basic) on the same address

Perhaps there is some reverse proxy magic I can do with haproxy.  I'll have to look at how much https encodes that path

**Comment by scsibug** [comment]
I still think this is valuable within a websocket, since, in theory, a single host could be running many relays at the same domain. so using a static path or well-known uri would be a bit of a hassle to associate with the particular relay.  This makes it super clear that whatever you have a socket open to, you can grab important metadata about that exact relay.

**Comment by scsibug** [comment]
Perhaps a dual approach of using the well-known uri approach to provide a directory of relays running on a domain (1 or more, with some of the server info fields already discussed).  As well as the websocket command for getting the latest information about relays you have already decided to use and are connected to.  See https://github.com/Vroo/well-known-uri-appspecific/blob/main/well-known-uri-for-application-specific-purposes.txt for an example of a location that could be used on the http side.

**Comment by melvincarvalho** [comment]
Yes
FYI: well-known can also be a directory with a hierarchy e.g. is 

`/.well-known/ni/sha-256/<hash> `

See: [naming things with hashes](https://datatracker.ietf.org/doc/html/rfc6920)

**Comment by fiatjaf** [comment]
What about an HTTP request with `Accept: application/nostr+json` on the same path that is serving the websocket?

**Comment by scsibug** [comment]
That seems pretty ideal, I will go with that.

**Comment by melvincarvalho** [comment]
The theory goes that anything on a URL should give the same data, *more or less*, for whatever the accept header is

Reason being is that people download, scrape, cache, reason, on the data on a per-URL basis, so if you get different things based on the header, it will confuse some clients, or downstream systems

So would possibly be better on a separate path than `/`

**Comment by scsibug** [comment]
Well, I guess the server metadata is a representation of the server in some sense.  My vote is to keep it simple and use the same uri exactly, but open to proposals otherwise that would be straightforward.

**Comment by melvincarvalho** [comment]
@scsibug yes, definitely agree with keeping it simple.  And getting something working, is the more important thing.  So my comments are mainly just informational

I'll point out that an html root isnt *always* a page about the server.  

And there's also [Web Host Metadata](https://datatracker.ietf.org/doc/html/rfc6415) which can be put at `/.well-known/host-meta[.json]`

**Comment by scsibug** [comment]
@melvincarvalho definitely - I think we are saying it should be at the same path the websocket is on, which does not have to be /, it could be /nostr, /ws, or whatever.  I do not want to force it to always be /.

**Comment by scsibug** [comment]
I've taken out the "public_write" attribute, because I couldn't figure how it would work in practice.  I think the rest of the metadata is important and good enough for now.  Permissions should probably remain out-of-band at the moment.

**Comment by scsibug** [comment]
An example implementation is available through nostr-rs-relay.

```bash
$ curl -H "Accept: application/nostr+json" https://nostr-pub.wellorder.net/ 
```
```json
[
  "NOSTR_SERVER_INFO",
  {
    "name": "Public Wellorder Relay",
    "descr": "Public relay for nostr development and use.\n\nTesting the latest bleeding edge Nostr features.",
    "pubkey": "296aab577a2b2446fb6ae0dccc3e174d380984e4c967dc4bfd53f54e1f6e9b92",
    "email": "scsibug@imap.cc",
    "supported_nips": [
      "NIP-01"
    ],
    "software": "https://git.sr.ht/~gheartsfield/nostr-rs-relay",
    "version": "0.3.2"
  }
```

**Comment by melvincarvalho** [comment]
Suggest adding the wss server in there too:

```JSON
  {
    "id": "wss://nostr-pub.wellorder.net",
    "name": "Public Wellorder Relay",
    "descr": "Public relay for nostr development and use.\n\nTesting the latest bleeding edge Nostr features.",
    "pubkey": "296aab577a2b2446fb6ae0dccc3e174d380984e4c967dc4bfd53f54e1f6e9b92",
    "email": "scsibug@imap.cc",
    "supported_nips": [
      "NIP-01"
    ],
    "software": "https://git.sr.ht/~gheartsfield/nostr-rs-relay",
    "version": "0.3.2"
  }
```

Question:  `NOSTR_SERVER_INFO` or `NOSTR_RELAY_INFO`?

**Comment by scsibug** [comment]
I will swap to NOSTR_RELAY_INFO, good catch.  descr or description is fine, open to either.

Is the id not implied by the url you are already getting the info document from?  or are you proposing that people would publish an arbitrary URL with the info document, and have the ID point them somewhere different?  Would that not be better handled with HTTP redirects?

**Comment by melvincarvalho** [comment]
> Is the id not implied by the url you are already getting the info document from

Not necessarily, as you can have many JSON objects on a page, and nested objects

Adding it explicitly is a good practice IMHO in the decentralized world, as it helps to break the connection between the data and the transport

**Comment by scsibug** [comment]
OK, that makes sense.  I will add it.

**Comment by scsibug** [comment]
Latest changes in the PR have this look like the following (live example from https://nostr-pub.wellorder.net/):

```json
{
  "id": "wss://nostr-pub.wellorder.net/",
  "name": "Public Wellorder Relay",
  "description": "Public relay for nostr development and use.\n\nTesting the latest bleeding edge Nostr features.",
  "pubkey": "35d26e4690cbe1a898af61cc3515661eb5fa763b57bd0b42e45099c8b32fd50f",
  "email": "scsibug@imap.cc",
  "supported_nips": [
    1
  ],
  "software": "https://git.sr.ht/~gheartsfield/nostr-rs-relay",
  "version": "0.3.3"
}
```

**Comment by fiatjaf** [comment]
I don't like the ID thing. What is the use case for this? Requiring an ID requires relays to be aware of their own URLs which is often a hard and tedious thing for no gain.

**Comment by melvincarvalho** [comment]
> I don't like the ID thing. What is the use case for this? Requiring an ID requires relays to be aware of their own URLs which is often a hard and tedious thing for no gain.

It could be optional then.  Then it's possible to have anonymous and light relays, which definitely will be a thing.

Normally a best practice to identify in the JSON object what you are talking about, it allows for caching, and transport over different protocols, as well as out of band.  It can be stored in the client and also retrieved with primary or foreign key lookups etc.

**Comment by fiatjaf** [comment]
I don't like any of these:

- best practices, because we must know the purpose of doing the things, not just do them blindly because they are best practices
- caching, because it makes no sense in this context
- transport over different protocols, because one way of doing things is better than multiple ways, see http://scripting.com/2017/05/09/rulesForStandardsmakers.html

**Comment by melvincarvalho** [comment]
@fiatjaf fair enough

Does making it optional solve it, as I'd like to put it in my public node and also be part of nostr

**Comment by scsibug** [comment]
Simce all of these attributes are optional (as well as the NIP in general), clients are going to have generate their own way of associating this  data with a relay.  And I am unsure of what it means for a relay to publish an `id` that differs from its actual URL.

I do agree that json objects which contain an app-specific  unique identifier (like a URL or uuid) are more useful, although it does impose some validation logic on clients (ensuring a relay does not attempt to overwrite a pubkey for someone else's relay).  In practice this may suggest that the only legit value for `id` is the URL you got it from (or the same origin at minimum), which suggests that clients should be adding this themselves if they want to track/cache/index it.

If there isn't a clear and unambiguous safe answer here, I am OK with dropping it, and making clients track the URL or unique identifier themselves.

**Comment by fiatjaf** [comment]
I think you should be able to put anything in your JSON, but the spec should only standardize things **required for compatibility**.

**Comment by scsibug** [comment]
Email has now been replaced with "contact".  A recommendation is to place a URI (such as mailto: or https:, or ever tel:) in that field, so this supports more options and is not limited to email.  It is also possible to place plain text there, to direct a user manually ("channel #nostr on irc server irc.example.com").
