### ISSUE TITLE
Maximally easy to use

### ISSUE THREAD

**Issue by vinliao** [fiatjaf/nostr#57]
On Bitcoin, losing your key means you lose your money. On system like nostr, losing your key means permanently losing the identity and reputation you've built up. Not nice.

Twitter seems to have perfected the ease-of-use for users. Many innovations can happen on the wallet side. What sort of extensions, projects, and NIPs is no one working on that would help nostr achieve Twitter-like ease-of-use?

**Comment by fiatjaf** [comment]
To be honest I don't know exactly what you mean. We have some ideas for easing key management but most of them are out of the scope of the protocol per se.

The great thing about using the BIP340 signature scheme is that we can reuse Bitcoin libraries for threshold signatures, collaborative signatures and key tweaking magic to make some nice constructs that safeguard identity, but before trying to execute any we would have to see some more usage of Nostr first.

**Comment by vinliao** [comment]
You know what, I think it's better to just build rather than asking philosophical question like I did...
