### ISSUE TITLE
Change "<id>" to "<subscription id>" in NIP-01

### ISSUE THREAD

**Issue by vinliao** [fiatjaf/nostr#66]
In NIP-01, there's a `"REQ"` message from client to relay, which looks like this: `["REQ", <id>, <filter JSON>...]`. The `<id>` part confused me a bit (took me some time to figure out what it is). I thought it was event id.

I think it would be less confusing if it's renamed to `<subscription id>` or `<subscription string>`. Not a critical issue; just a semantic change to make it easier to understand.

**Comment by scsibug** [comment]
Agreed, it would be good to disambiguate from the event id.
