### ISSUE TITLE
Alias inside Nostr

### ISSUE THREAD

**Issue by vinliao** [fiatjaf/nostr#70]
It's sometimes desirable to link a main identity with an alt. Two pubkeys (main and alt) can be cryptographically linked by creating these two events:

`main event` (created by main):
```
{
  "id": <main event id>
  "pubkey": <main's pubkey>,
  "created_at": <unix timestamp in seconds>,
  "kind": <integer>,
  "tags": [
    ["p", <alt's pubkey>],
  ]
  "content": <empty string>,
  "sig": <64-bytes signature of the sha256 hash of the serialized event data, which is the same as the "id" field>,
}
```

`alt event` (created by alt):
```
{
  "id": <alt event id>
  "pubkey": <alt's pubkey>,
  "created_at": <unix timestamp in seconds>,
  "kind": <integer>,
  "tags": [
    ["e", <main event id>],
    ["p", <main's pubkey>],
  ]
  "content": <empty string>,
  "sig": <64-bytes signature of the sha256 hash of the serialized event data, which is the same as the "id" field>,
}
```

Looked another way: alt event is a reply to main event.

A main or alt can prove its main-alt relationship by providing `main event` and `alt event`; the main-alt relationship is invalid until `alt event` is present.

These main-alt relationship can also be privately announced through NIP-04, which can be used to have private chats. Say Alice wants to chat with Bob, but Bob is a super-controversial character that has been cancelled. If Alice is caught chatting with Bob, she's also gonna get cancelled. Alice can chat privately with Bob through Nostr by doing this:

1. Alice creates an alt, encrypts her `main event` and `alt event` with NIP-04, then sends it to Bob's publicly-known pubkey with a random key.
2. Bob creates an alt, encrypts his `main event` and `alt event` with NIP-04, then send it to Alice's alt with his alt.
3. Both communicates with their alt: no one knows who these alts are, but both Alice and Bob has cryptographic proof that the alts they're talking to are legit.

Nostr-native alias is a simple building-block that has use-cases. Can this alias-creation scheme be simplified further?

**Comment by fiatjaf** [comment]
I like this. Can you write it as a NIP? I would just specify a new event kind number for these two "linkage" events.

But maybe we need to wait for input from other people, maybe someone has constructive comments.

This also fixes NIP04, maybe?

The question someone will probably ask: can you revoke an alt later?

**Comment by vinliao** [comment]
PR at #71. I think this idea has to be attacked as hard as possible, from as much angle as possible, before it's turned into a NIP. There might be a better way to do it, there might be a fatal flaw, who knows.
