### ISSUE TITLE
Poor guarantees that receipient will receive an event meant for them

### ISSUE THREAD

**Issue by jb55** [fiatjaf/nostr#76]
I'm thinking of a situation where there are many relays, and perhaps your client connects to some ransom subset of them. There doesn't appear to be any way to ensure that a particular event makes it to a specific user.

Let's say I publish a message to relays I'm connected to, and I want to send a DM to another pubkey on the network. afaict there is no way of knowing if they can see that message, because I do not know what relays they are connected to.

activitypub solves this since you know where a particular user's inbox is, so you can send an event directly to that server. Are there proposed solutions on how nostr might solve this?

**Comment by fiatjaf** [comment]
If you can read any events from your friend ever that might give you a good idea of what relays they are using, specially if it's a `recommend_server` kind of event, or a `contact_list` (I was also thinking we could have another special event kind just for one publishing the set of relays they're using and with each "policy" for each, as means of backing that up to be reused on other clients, but also for sharing it with the world).

**Comment by fiatjaf** [comment]
However from my understanding this is ultimately not 100% solvable.

If you ask the Slashtags people they will say that's the crucial problem of Nostr: that you can't be guaranteed to find someone else just by their public key, and they will tell you their DHT fixes this.

If you ask the DID people they will tell you the "DID Methods" exist to solve this by pushing some peer metadata into some shitcoin blockchain or into IPFS.

I don't think these solutions are as reliable or as honorable as their proponents say they are, and I don't think they deserve a place at the core of Nostr, but they can also be used on Nostr as extensions, like the DNS names are being used, for example.

But honestly I think Nostr can go a long way without using any of these tricks, just getting events from known relays + manually searching when necessary.
